### ISSUE TITLE
Release in sync with `software.amazon.awssdk:secretsmanager`?

### ISSUE THREAD

**Issue by pmeinhardt** [aws/aws-secretsmanager-caching-java#114]
Hello there. 👋🙂

I was wondering why this package is not kept in sync with new releases of `software.amazon.awssdk:secretsmanager`.
It seems like this is the only dependency (outside of test dependencies).

Seems like releasing a new version of this package could be automatically published whenever a new version of the underlying AWS SDK drops. This would make it easier to stay up-to-date and receive all the latest versions of transitive dependencies in the SDK.

At the moment of writing this, the SDK version used here is still `2.20.93`, while the SDK has moved on to `2.23.17` and includes a couple of security updates.

Kind regards

**Comment by jbct** [comment]
When security-related issues arise, we are notified and will roll the change into another release update. Outside of that, when we do a release, we will often update dependencies as well. Is there something specific you're looking for in the next SDK version that isn't available in 2.20?
