### ISSUE TITLE
currentTimeMillis is not monotonic

### ISSUE THREAD

**Issue by davecramer** [aws/aws-secretsmanager-caching-java#25]
https://github.com/aws/aws-secretsmanager-caching-java/blob/68fe7f3929980241fa02319054cd49292f6fd01e/src/main/java/com/amazonaws/secretsmanager/caching/cache/SecretCacheItem.java#L106

System.nanoTime() is better

**Comment by simonmarty** [comment]
From [this SO thread](https://stackoverflow.com/questions/351565/system-currenttimemillis-vs-system-nanotime), it seems that on Windows, `currentTimeMillis` has a resolution of about 10ms. Have you managed to create a reproducible situation where using `currentTimeMillis` causes unwanted behavior?

**Comment by davecramer** [comment]
The problem is it is not monotonic https://stackoverflow.com/questions/2978598/will-system-currenttimemillis-always-return-a-value-previous-calls#:~:text=The%20short%20answer%20is%20no%2C%20System.currentTimeMillis%20%28%29%20is,case%20of%20clock%20adjustments%20%28e.g.%20via%20NTP%20%29.

**Comment by simonmarty** [comment]
Unix time stamps do not contain any timezone data. NTP clock adjustments happen at most at the second-scale (for leap seconds), which should not affect the behavior of this library.

**Comment by davecramer** [comment]
Thanks, you are absolutely correct.
