### ISSUE TITLE
Reconcile README with AWS documentation

### ISSUE THREAD

**Issue by githorse** [aws/aws-secretsmanager-caching-java#7]
After reading the [AWS Secrets Manager User Guide on Client-Side Caching](https://docs.aws.amazon.com/secretsmanager/latest/userguide/manage_retrieve-secret.html#use-client-side-caching-components) and the [README](https://github.com/aws/aws-secretsmanager-caching-java/blob/master/README.md) on this project, I'm confused. The user guide implies that: 

*[The caching client] should retrieve and update the secret value from Secrets Manager only when the cached value no longer works and you get an "Access Denied" error message because Secrets Manager rotated the credentials.* 

-- i.e., every few hours or days, maybe. But this project is an in-process cache, I think. It's not going to persist my secrets beyond whatever process creates the `SecretCache` object, right? Not long enough for them to get rotated out, in most cases.

The User Guide also mentions "installing" the client, as if it's a standalone CLI executable. So I'm not actually sure if we're talking about the same thing here or not.

If anyone else shares my confusion, could either the User Guide or the README be updated to clarify this?

**Comment by gbailey** [comment]
For your first question about the in-process cache, the answer is yes.  It will only cache within the context of the specific instance of SecretCache within the process.  Will this be long enough to need logic for handling rotation?  It depends.  There are use cases where long lived processes use secrets that get rotated.  Those long lived processes will find the most benefit from an in-process cache of secrets.

I will request that the User Guide is updated to not use 'install' when discussing the use of this client-side caching library.

**Comment by githorse** [comment]
Sounds good. Some additional language in the User Guide to clarify the in-process part would also be very helpful. Maybe something along the lines of (new text in bold):

Secrets Manager has created a client-side component that implements these best practices to simplify your creation of code that accesses secrets stored in AWS Secrets Manager. **Note that the client-side component is an in-process cache and will not cache secrets beyond the lifetime of a single process.**
